#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Mar 27, 2016 11:12:07 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background {#f2d3bf} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x409+145+237
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1916 1053
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Client_TopLevel"
    vTcl:DefineAlias "$top" "Client_Toplevel" vTcl:Toplevel:WidgetProc "" 1
    button $top.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Withdraw 
    button $top.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Deposit 
    button $top.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Transfer 
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text OK 
    vTcl:DefineAlias "$top.but40" "btn_ok" vTcl:WidgetProc "Client_Toplevel" 1
    button $top.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Cancel 
    vTcl:DefineAlias "$top.but41" "btn_cancel" vTcl:WidgetProc "Client_Toplevel" 1
    text $top.tex43 \
        -background white -font font10 -foreground black -height 272 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -takefocus 0 -width 414 -wrap word 
    .top36.tex43 configure -font font10
    .top36.tex43 insert end text
    spinbox $top.spi44 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font font10 -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -takefocus 0 \
        -to 100.0 -values {200 {}} 
    vTcl:DefineAlias "$top.spi44" "spinbox_amount" vTcl:WidgetProc "Client_Toplevel" 1
    menu $top.m45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font font10 -foreground {#000000} -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but37 \
        -in $top -x 470 -y 60 -width 79 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but38 \
        -in $top -x 470 -y 120 -width 79 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but39 \
        -in $top -x 470 -y 180 -width 79 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but40 \
        -in $top -x 50 -y 360 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.but41 \
        -in $top -x 470 -y 360 -width 89 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.tex43 \
        -in $top -x 30 -y 30 -width 414 -height 272 -anchor nw \
        -bordermode ignore 
    place $top.spi44 \
        -in $top -x 140 -y 330 -width 205 -height 21 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

